import aboutBrandImg from "../assets/about-brand.jpg";

import { Product } from "./products";

export const safariProducts: Product[] = [
  { id: "sf1", name: "Tropical Coral Hi-Low Dress", price: 0, image: aboutBrandImg, category: "Hi-Low Dress", style: "hi low dress", color: "Pink" },
  { id: "sf2", name: "Tropical Coral Open Frill Dress", price: 0, image: aboutBrandImg, category: "Open Frill Dress", style: "front open frill dress", color: "Pink" },
  { id: "sf3", name: "Athena Long Shirt Dress - Blue", price: 0, image: aboutBrandImg, category: "Long Shirt Dress", style: "long dress", color: "Blue" },
  { id: "sf4", name: "Athena Gypsy Top - Blue", price: 0, image: aboutBrandImg, category: "Gypsy Top", style: "gypsy dress", color: "Blue" },
  { id: "sf5", name: "Athena Box Kaftan - Blue", price: 0, image: aboutBrandImg, category: "Box Kaftan", style: "box kaftan", color: "Blue" },
  { id: "sf6", name: "Athena Gypsy Top - Blue Print", price: 0, image: aboutBrandImg, category: "Gypsy Top", style: "gypsy top", color: "Blue" },
  { id: "sf7", name: "Athena Tank Top & Palazzo Pant - Blue", price: 0, image: aboutBrandImg, category: "Tank Top + Plazo Pant", style: "top and plazo pant", color: "Blue" },
  { id: "sf8", name: "Sorento Kimono & Bag - Off White", price: 0, image: aboutBrandImg, category: "Kimono and Bag", style: "kimono and bag", color: "Off White" },
  { id: "sf9", name: "Brown Leopard Shirt & Palazzo", price: 0, image: aboutBrandImg, category: "Shirt and Palazo", style: "shirt and plazo pant", color: "Brown" },
  { id: "sf10", name: "Brown Leopard Tank Top & Palazzo", price: 0, image: aboutBrandImg, category: "Tank Top + Plazo Pant", style: "tank top and plazo pant", color: "Brown" },
  { id: "sf11", name: "Aqua Leopard Shirt & Palazzo - Black", price: 0, image: aboutBrandImg, category: "Shirt and Palazo", style: "shirt and plazo pant", color: "Black" },
  { id: "sf12", name: "Pardus Kimono & Bag - Brown", price: 0, image: aboutBrandImg, category: "Kimono and Bag", style: "kimono and bag", color: "Brown" },
  { id: "sf13", name: "Merika Long Shirt Dress - Blue", price: 0, image: aboutBrandImg, category: "Long Shirt Dress", style: "long shirt", color: "Blue" },
  { id: "sf14", name: "Merika Long Shirt Dress - Black", price: 0, image: aboutBrandImg, category: "Long Shirt Dress", style: "long dress", color: "Black" },
  { id: "sf15", name: "Tropical Shirt & Palazzo - Pink", price: 0, image: aboutBrandImg, category: "Shirt and Palazo", style: "shirt and plazo pant", color: "Pink" },
  { id: "sf16", name: "Athena Hi-Low Dress - Blue", price: 0, image: aboutBrandImg, category: "Hi-Low Dress", style: "hi low dress", color: "Blue" },
  { id: "sf17", name: "Athena Shirt & Palazzo - Blue", price: 0, image: aboutBrandImg, category: "Shirt and Palazo", style: "shirt and plazo pant", color: "Blue" },
  { id: "sf18", name: "Sorento Gypsy Top - Off White", price: 0, image: aboutBrandImg, category: "Gypsy Top", style: "gypsy dress", color: "Off White" },
  { id: "sf19", name: "Sorento Gypsy Top & Palazzo - Off White", price: 0, image: aboutBrandImg, category: "Gypsy Top and Plazo Pant", style: "gypsy top and plazo pant", color: "Off White" },
  { id: "sf20", name: "Sorento Tank Top & Palazzo - Off White", price: 0, image: aboutBrandImg, category: "Tank Top + Plazo Pant", style: "tank top and plazo pant", color: "Off White" },
  { id: "sf21", name: "Brown Leopard Kimono & Bag", price: 0, image: aboutBrandImg, category: "Kimono and Bag", style: "kimono and bag", color: "Brown" },
  { id: "sf22", name: "Brown Leopard Gypsy Top", price: 0, image: aboutBrandImg, category: "Gypsy Top", style: "Gypsy top", color: "Brown" },
  { id: "sf23", name: "Black Leopard Long Shirt Dress", price: 0, image: aboutBrandImg, category: "Long Shirt Dress", style: "long dress", color: "Black" },
  { id: "sf24", name: "Black Leopard Shirt & Palazzo", price: 0, image: aboutBrandImg, category: "Shirt and Palazo", style: "shirt and plazo pant", color: "Black" },
  { id: "sf25", name: "Black Leopard Gypsy Top", price: 0, image: aboutBrandImg, category: "Gypsy Top", style: "Gypsy top", color: "Black and white" },
  { id: "sf26", name: "Black Leopard Kimono & Bag - Skin", price: 0, image: aboutBrandImg, category: "Kimono and Bag", style: "kimono and bag", color: "Skin" },
  { id: "sf27", name: "Tiger Shirt Tank Top & Palazzo - Skin", price: 0, image: aboutBrandImg, category: "Tank Top + Plazo Pant", style: "plazo pant", color: "Skin" },
  { id: "sf28", name: "Aqua Leopard Short Dress - Black", price: 0, image: aboutBrandImg, category: "Short Dress", style: "short dress", color: "Black" },
  { id: "sf29", name: "Aqua Leopard Coral Front - Black", price: 0, image: aboutBrandImg, category: "Coral Front", style: "coral front", color: "Black" },
  { id: "sf30", name: "Aqua Leopard Hi-Low Dress - Black", price: 0, image: aboutBrandImg, category: "Hi-Low Dress", style: "hi low dress", color: "Black" },
  { id: "sf31", name: "Aqua Leopard Long Shirt Dress - Black", price: 0, image: aboutBrandImg, category: "Long Shirt Dress", style: "long dress", color: "Black" },
  { id: "sf32", name: "Aqua Leopard Long Box Kaftan - Black", price: 0, image: aboutBrandImg, category: "Long Box Kaftan", style: "box kaftan", color: "Black" },
  { id: "sf33", name: "Aqua Leopard Kimono & Bag - Black", price: 0, image: aboutBrandImg, category: "Kimono and Bag", style: "kimono and bag", color: "Black" },
  { id: "sf34", name: "Aqua Leopard Tank Top & Palazzo - Black", price: 0, image: aboutBrandImg, category: "Tank Top + Plazo Pant", style: "tank top and plazo", color: "Black" },
  { id: "sf35", name: "Paradus Long Frill Dress - Brown", price: 0, image: aboutBrandImg, category: "Long Frill Dress", style: "long frill dress", color: "Brown" },
  { id: "sf36", name: "Paradus Short Frill Dress - Brown", price: 0, image: aboutBrandImg, category: "Short Frill Dress", style: "short frill dress", color: "Brown" },
  { id: "sf37", name: "Paradus Hi-Low Dress - Brown", price: 0, image: aboutBrandImg, category: "Hi-Low Dress", style: "High low dress", color: "Brown" },
  { id: "sf38", name: "Paradus Tank Top & Palazzo - Brown", price: 0, image: aboutBrandImg, category: "Tank Top + Plazo Pant", style: "tank top and plazo", color: "Brown" },
];
